### ISSUE TITLE
Can't set Content-Type for object storage

### ISSUE THREAD

**Issue by nirvdrum** [oracle/oci-ruby-sdk#10]
It's not possible to set the `Content-Type` for an object being stored into OCI object storage due to a difference in Symbol vs String keys when preparing request headers for the `OCI::ObjectStorage::ObjectStorageClient#put_object` call.

https://github.com/oracle/oci-ruby-sdk/blob/8710456a48a59910396add4e98677c2627491c9b/lib/oci/object_storage/object_storage_client.rb#L1538 requires the caller to supply the key as a Symbol (i.e., `:content_type`).

However, https://github.com/oracle/oci-ruby-sdk/blob/8710456a48a59910396add4e98677c2627491c9b/lib/oci/object_storage/object_storage_client.rb#L1548 assumes the key is a String (i.e., `'content-type`) and ends up always writing the value `'application/octet-stream'`.

The line `header_params['content-type'] ||= 'application/octet-stream'` should probably be `header_params[:'content-type'] ||= 'application/octet-stream'`.

**Comment by andy-miles** [comment]
Thank you for catching this bug.  I'll work on including the fix for the next release.

**Comment by andy-miles** [comment]
The 2.3.7 release includes [the fix](https://github.com/oracle/oci-ruby-sdk/blob/25acf2c0dec47737c3076db7a73bea30e24ca3ac/lib/oci/object_storage/object_storage_client.rb#L1543-L1553) to set the `content-type`.
