### ISSUE TITLE
Add a note on thread-safety

### ISSUE THREAD

**Issue by nirvdrum** [oracle/oci-ruby-sdk#13]
Please consider adding a note on thread-safety. Upon brief inspection it looked like the gem is not thread-safe, but I couldn't find any documentation indicating one way or another. To be safe, I opted to use the [connection pool](https://rubygems.org/gems/connection_pool) gem and make each request in a reserved, isolated connection

**Comment by andy-miles** [comment]
The SDK clients rely on the Net::HTTP library for making connections.  As such, I would not assume that such built-in libraries are thread safe as underlying implements on different platforms can vary.

Here's an interesting thread regarding this question: https://www.ruby-forum.com/topic/174086#762788

Per your suggestion, I'll update the documentation for the clients to indicate that clients are not assumed to be thread safe.

**Comment by andy-miles** [comment]
All clients in the 2.3.7 release [now includes a note](https://github.com/oracle/oci-ruby-sdk/blob/25acf2c0dec47737c3076db7a73bea30e24ca3ac/lib/oci/object_storage/object_storage_client.rb#L34) about thread-safety.
