### ISSUE TITLE
OCI::ObjectStorage::ObjectStorageClient#get_object improperly deserializes JSON documents

### ISSUE THREAD

**Issue by nirvdrum** [oracle/oci-ruby-sdk#14]
I have a JSON document that I've stored in OCI object storage with a `Content-Type` of `application/json`. When I call `get_object`, I'd expect to get the raw contents of the document body. The documentation is a bit unclear about this because it sounds as if some auto-deserializing might be intended. The documented return value for `get_object` is `A Response object with data of type String if response_target and block are not given, otherwise with nil data `. Looking at the instance attribute summary for `Response#data` says `The body of the response.`. While looking at the instance attribute details for `Response#data` says `The body of the response. For example, this may contain a User object, or a list of Users.`

Nothing explicitly says that the response body will be deserialized. The instance attribute details description hints at it by saying a `User object, or a list of Users` may be returned. But elsewhere it looks like the raw data of the response body will be returned. At best, there's a documentation issue here.

The real problem I'm encountering is the document body is deserialized. Moreover, it uses the extra option `symbolize_names` to turn the String keys into Symbols, which may not be expected. But the worst part is this deserialized object then has `to_s` called on it and *that* is used as the `Response#data` object.

In my case, I have an array of dictionaries. Instead of getting back something like `[{ "my.key" : "my.value" }]` I get back something like `[{ :"my.key" => "my.value" }]`. This returned string isn't valid JSON. There's really not much I can do with that return value other than `eval` it to try to get back the object structure I really want.

The workaround for the time being is to set the `Content-Type` header to `text/plain`. This is logically incorrect, but it prevents the `oci` library from trying to deserialize the response body.

**Comment by andy-miles** [comment]
I'll look into writing some tests to reproduce this issue.  Thanks for bringing this to our attention.

**Comment by andy-miles** [comment]
After investigating, I was able to verify that net::http by default will convert `application/json` to a hash when the corresponding `accept` header is defined accordingly for a ObjectStorageClient#get_object() call.

### Reproduction:
```
json_hash = object_storage_client.get_object(
  namespace,
  bucket_name,
  object_name,
  accept: 'application/json'
).data

pp json_hash
```

Output with example JSON object:
```
"{:glossary=>{:title=>\"example glossary\", :GlossDiv=>{:title=>\"S\", :GlossList=>{:GlossEntry=>{:ID=>\"SGML\", :SortAs=>\"SGML\", :GlossTerm=>\"Standard Generalized Markup Language\", :Acronym=>\"SGML\", :Abbrev=>\"ISO 8879:1986\", :GlossDef=>{:para=>\"A meta-markup language, used to create markup languages such as DocBook.\", :GlossSeeAlso=>[\"GML\", \"XML\"]}, :GlossSee=>\"markup\"}}}}}"
```
### Recommendation:

If you want to explicitly return the JSON text instead, you want to define an `accept` header of `test/json` instead.


```
json_text = object_storage_client.get_object(
  namespace,
  bucket_name,
  object_name,
  accept: 'text/json'
).data

pp json_text
```

This outputs the same JSON as above, but as text:
```
"{\n" +
"    \"glossary\": {\n" +
"        \"title\": \"example glossary\",\n" +
"\t\t\"GlossDiv\": {\n" +
"            \"title\": \"S\",\n" +
"\t\t\t\"GlossList\": {\n" +
"                \"GlossEntry\": {\n" +
"                    \"ID\": \"SGML\",\n" +
"\t\t\t\t\t\"SortAs\": \"SGML\",\n" +
"\t\t\t\t\t\"GlossTerm\": \"Standard Generalized Markup Language\",\n" +
"\t\t\t\t\t\"Acronym\": \"SGML\",\n" +
"\t\t\t\t\t\"Abbrev\": \"ISO 8879:1986\",\n" +
"\t\t\t\t\t\"GlossDef\": {\n" +
"                        \"para\": \"A meta-markup language, used to create markup languages such as DocBook.\",\n" +
"\t\t\t\t\t\t\"GlossSeeAlso\": [\"GML\", \"XML\"]\n" +
"                    },\n" +
"\t\t\t\t\t\"GlossSee\": \"markup\"\n" +
"                }\n" +
"            }\n" +
"        }\n" +
"    }\n" +
"}\n"
```
