### ISSUE TITLE
Already initialized constant warning

### ISSUE THREAD

**Issue by lenon** [oracle/oci-ruby-sdk#45]
Hi,
Since the release of 2.7.0, I'm seeing the following warning:

```ruby
.../oci-ruby-sdk-62498bb3f567/lib/oci/identity/models/base_tag_definition_validator.rb:20: warning: already initialized constant OCI::Identity::Models::BaseTagDefinitionValidator::VALIDATOR_TYPE_ENUM
.../oci-ruby-sdk-62498bb3f567/lib/oci/identity/models/base_tag_definition_validator.rb:21: warning: previous definition of VALIDATOR_TYPE_ENUM was here
```

It seems to be caused by this code:

https://github.com/oracle/oci-ruby-sdk/blob/ac8a0960f5573d260c2b242c8cff1ba0f529be13/lib/oci/identity/models/base_tag_definition_validator.rb#L19-L24

`VALIDATOR_TYPE_ENUM` is declared twice, first by `VALIDATOR_TYPE_ENUM = 'ENUM'.freeze` and then redeclared as `VALIDATOR_TYPE_ENUM = [ ... ]`.

**Comment by jyotisaini** [comment]
Thanks Lenon. I will take a look at it.

**Comment by dvisamse** [comment]
Am blocked on this as well. Is there a fix or workaround for this?

**Comment by jyotisaini** [comment]
Hi @dvisamse It should not block you from using any SDK functionality. Its just a warning. In the mean time we are working on the fix.

**Comment by yogeshlc** [comment]
Is this warning issue got fixed? I am also seeing this warning and it is annoying? Is there any workaround to suppress this warning?

**Comment by justintsteele** [comment]
+1 on this.  Any update on this fix?

**Comment by ZiyaoQiao** [comment]
Hi, we're working on this fix, will release a new version with this fix soon

**Comment by ZiyaoQiao** [comment]
@dvisamse @yogeshlc @justintsteele This issue have been fixed in today's release, https://github.com/oracle/oci-ruby-sdk/releases/tag/v2.10.0
I'm going to close this issue, for any questions regarding this issue, feel free to reopen and let us know
