### ISSUE TITLE
oci-ruby-sdk update with latest API changes

### ISSUE THREAD

**Issue by racx** [oracle/oci-ruby-sdk#46]
We noticed that the OCI API has new updates, like copy boot volume snapshots from region to another https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/BootVolumeBackup/CopyBootVolumeBackup but the ruby SDK is still falling behind to these new updates since November.

We were obliged to fork this repo to support this feature: https://github.com/racx/oci-ruby-sdk

Will this repo be updated any time soon?

Thank you

**Comment by jyotisaini** [comment]
Hi @racx , its correct. Ruby-SDK  does not support these updates as of now. Ruby SDK is currently in maintenance mode, what it means is we have reduced release cycle from weekly to quarterly. I ll open a ticket to do a ruby release and will update here once its done.

**Comment by jyotisaini** [comment]
Hi @racx : We have released a new version of ruby SDK ( 2.8.0) with all the latest changes. Closing this issue.
