### ISSUE TITLE
OCI ruby SDK dont support Instance metadata V2

### ISSUE THREAD

**Issue by sosiskin2000** [oracle/oci-ruby-sdk#52]
Support for using instance metadata API v2 for instance principals authentication - don't working.

- There is no usage location /v2  - https://github.com/oracle/oci-ruby-sdk/blob/master/lib/oci/auth/signers/instance_principals_security_token_signer.rb
- Using ruby gem shows
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/oci-2.8.0/lib/oci/identity/models/base_tag_definition_validator.rb:23: warning: previous definition of VALIDATOR_TYPE_ENUM was here

      * chef_gem[oci] action install (up to date)
      
      ================================================================================
      Error executing action `auth_util` on resource 'vault[get ar-tran-token]'
      ================================================================================
      
      OpenSSL::PKey::RSAError
      -----------------------
      Neither PUB key nor PRIV key: nested asn1 error

**Comment by jodoglevy** [comment]
Hi @sosiskin2000 - yesterday we released a new version of the Ruby SDK which should fix this issue. Can you try that out and let us know if you're still encountering the same problem?

**Comment by jodoglevy** [comment]
@sosiskin2000  since we haven't heard from you in a while, I'm going to close this, as it should be fixed. Please feel free to reopen this if you are still encountering the issue
