### ISSUE TITLE
Thread safe

### ISSUE THREAD

**Issue by fcecagno** [oracle/oci-ruby-sdk#64]
Hi, is the SDK thread safe? I couldn't find this information in the docs.
Thanks!

**Comment by ZiyaoQiao** [comment]
Hi, all service clients in Ruby SDK use Net::HTTP library for making connections, it's not thread-safe. 
https://github.com/oracle/oci-ruby-sdk/blob/master/lib/oci/object_storage/object_storage_client.rb#L38

**Comment by ZiyaoQiao** [comment]
@fcecagno we've added a thread-safe section in README. We're closing this issue and if you have any questions, feel free to reopen this. Thanks!

**Comment by fcecagno** [comment]
Thank you for your information.
